language: python
python:
    - "2.7"
    - "3.6"
install:
    - pip install flask requests vk 

script:
    python Bot.py bdist_wheel

deploy:
    provider: releases
    skip_cleanup: true
    api_key: ${GITHUB_TOKEN}
    file_glob: true
    file:
        - Bot.py

notifications:
    email:  
        recipients:  
        - mel5566@mail.ru  
        on_success: always  
        on_failure: always
